### ISSUE TITLE
pukes on valid base64 with bad data

### ISSUE THREAD

**Issue by kch** [heroku/ssl-doctor#11]
this guy here:

```
-----BEGIN CERTIFICATE-----
MIIFRjCCBC6gAwIBAgIDFeZ9MA0GCSqGSIb3DQEBBQUAMDwxCzAJBgNVBAYTAlVT
MRcwFQYDVQQKEw5HZW9UcnVzdCwgSW5jLjEUMBIGA1UEAxMLUmFwaWRTU0wgQ0Ew
HhcNMTQxMDI4MDA1NzM4WhcNMTYxMDI5MTE0MjEwWjCBxTEpMCcGA1UEbrMgc0t3
eko1ektLMTdWVzNhd25tNDZOR21XajViSTFuRE8xEzARBgNVBAsTCkdUNTQwMjcz
MjUxMTAvBgNVBAsTKFNlZSB3d3cucmFwaWRzc2wuY29tL3Jlc291cmNlcy9jcHMg
KGMpMTQxLzAtBgNVBAsTJkRvbWFpbiBDb250cm9sIFZhbGlkYXRlZCAtIFJhcGlk
U1NMKFIpMR8wHQYDVQQDExZ3d3cuY29udHJhY3RwbHVzLmNvLmlsMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtHB3AYclbA6HWEUy9/MyPoDBCq/3v2Da
qJM0Sqblf31sYnLa7ZOQApsXrL4vfRE4oaBOEsKe7CgrCVXlxi5QmK56R3LNERbs
R14m1BZVWn6/jiX6GKrZx/N20de+gdkOYEOr7gNNjOcJYcGu06BJuGfWIyECZ+of
7uwk7kZRFR87ynYu0ft/nW3nwU20Jx6TmXi1uwap0CCaHQPSkDnx1S4n7Nno+oZx
/uLtHZmjR2fII6g6ZynMSHdrPbhiM5aV3hHk3EhiMfzJ+zPHADc8l5YSKo1LMiZW
lE7hxdO9fNhH+ATs2OAH0mmXOG5cVi3EYKtpTrtaYv4oFw/pGuwyoQIDAQABo4IB
xTCCAcEwHwYDVR0jBBgwFoAUa2k9ahhCSt2PAmU5/TUkhniRFjAwDgYDVR0PAQH/
BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjA1BgNVHREELjAs
ghZ3d3cuY29udHJhY3RwbHVzLmNvLmlsghJjb250cmFjdHBsdXMuY28uaWwwQwYD
VR0fBDwwOjA4oDagNIYyaHR0cDovL3JhcGlkc3NsLWNybC5nZW90cnVzdC5jb20v
Y3Jscy9yYXBpZHNzbC5jcmwwHQYDVR0OBBYEFEudD6nCrm2K3YPVBzORzWhiRafg
MAwGA1UdEwEB/wQCMAAweAYIKwYBBQUHAQEEbDBqMC0GCCsGAQUFBzABhiFodHRw
Oi8vcmFwaWRzc2wtb2NzcC5nZW90cnVzdC5jb20wOQYIKwYBBQUHMAKGLWh0dHA6
Ly9yYXBpZHNzbC1haWEuZ2VvdHJ1c3QuY29tL3JhcGlkc3NsLmNydDBMBgNVHSAE
RTBDMEEGCmCGSAGG+EUBBzYwMzAxBggrBgEFBQcCARYlaHR0cDovL3d3dy5nZW90
cnVzdC5jb20vcmVzb3VyY2VzL2NwczANBgkqhkiG9w0BAQUFAAOCAQEAmhGyY5rr
2z9a/Fr306AX/R+P3/ZF/zrjdUYho6plRIgegDLDpxlhlENV0aju2dd2kb5pUMv2
RzK/6uKoDr0ATPXH+8V0hogBtTO74Vj+r36SbkMW6nfdG/NeNse+eYDkA/3E3JOD
HwJBPLggoE4v8JKljm5BOCNWkyuWBCzs9M7iYZIVU9RV4g5RNOpv2QRMvVLY6rxp
jVjEANWfin9V0z1qTWsI0ICPSvBgQc3S1cZCJATALLAOfFnZUxXpDk/rFQEsMH81
aOwQfkpOVmKsSaoCx35Ph9n5sibZs1wLicsiL3NUir+60PExxpYQ0+RDjtKE9IZU
IgwgcQ2J5Z3efQ==
-----END CERTIFICATE-----
```

Will cause this:

    OpenSSL::X509::CertificateError - nested asn1 error:
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/certificate.rb:17:in `initialize'
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/certificate.rb:17:in `new'
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/certificate.rb:17:in `new'
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/pem_scanner.rb:36:in `block in certificates'
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/pem_scanner.rb:36:in `map'
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/pem_scanner.rb:36:in `certificates'
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/pem_scanner.rb:23:in `certs_from'
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/certificate.rb:25:in `scan'
    	/app/vendor/bundle/ruby/1.9.1/gems/ssltool-0.0.11/lib/ssltool/certificate_store.rb:80:in `resolve_chain'

**Comment by kch** [comment]
This will now give you

```
$ heroku certs:chain <(pbpaste)  
Resolving trust chain... failed
 !    No certificate given.
```

which sucks a bit less.
